# Generated by Django 6.0.4 on 2026-04-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationRule',
            fields=[
                ('rule_id', models.AutoField(primary_key=True, serialize=False)),
                ('target_type', models.CharField(max_length=50)),
                ('target_product_id', models.IntegerField(null=True)),
                ('boost_strength', models.FloatField(default=1.0)),
                ('min_fit_threshold', models.FloatField(default=0.3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_rules', to='packets.packet')),
            ],
            options={
                'db_table': 'moderation_rules',
            },
        ),
    ]
