# Generated by Django 4.2.30 on 2026-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationrule',
            name='max_gap_percent',
            field=models.FloatField(default=3.0),
        ),
        migrations.AddField(
            model_name='moderationrule',
            name='max_rank',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='moderationrule',
            name='target_rank',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='moderationrule',
            name='target_type',
            field=models.CharField(choices=[('boost', 'Boost'), ('suppress', 'Suppress'), ('push', 'Push'), ('promote_if_close', 'Promote If Close')], max_length=50),
        ),
    ]
