# Generated by Django 6.0.4 on 2026-04-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('packet_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmid', models.IntegerField(db_index=True)),
                ('category', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('launch_status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'packets',
            },
        ),
        migrations.CreateModel(
            name='RetailOutlet',
            fields=[
                ('outlet_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmid', models.IntegerField(db_index=True)),
                ('outlet_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('geography_zone', models.CharField(blank=True, max_length=50)),
                ('assigned_packets', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'retail_outlets',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('feature_id', models.AutoField(primary_key=True, serialize=False)),
                ('feature_code', models.CharField(max_length=50)),
                ('feature_name', models.CharField(max_length=100)),
                ('feature_type', models.CharField(max_length=50)),
                ('is_comparable', models.BooleanField(default=True)),
                ('is_scoreable', models.BooleanField(default=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='packets.packet')),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('dimension_id', models.AutoField(primary_key=True, serialize=False)),
                ('dimension_name', models.CharField(max_length=100)),
                ('priority', models.IntegerField(default=1)),
                ('seed_questions', models.JSONField()),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='packets.packet')),
            ],
            options={
                'db_table': 'dimensions',
            },
        ),
        migrations.CreateModel(
            name='BenefitMapping',
            fields=[
                ('mapping_id', models.AutoField(primary_key=True, serialize=False)),
                ('benefit_name', models.CharField(max_length=100)),
                ('feature_code', models.CharField(max_length=50)),
                ('weight_impact', models.FloatField()),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_mappings', to='packets.packet')),
            ],
            options={
                'db_table': 'benefit_mappings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_code', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product_url', models.URLField(blank=True)),
                ('crawl_status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='packets.packet')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='FinanceScheme',
            fields=[
                ('scheme_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheme_name', models.CharField(max_length=255)),
                ('valid_from', models.DateField(null=True)),
                ('valid_until', models.DateField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_schemes', to='packets.product')),
            ],
            options={
                'db_table': 'finance_schemes',
            },
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('value_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('normalized_value', models.FloatField(null=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='packets.feature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='packets.product')),
            ],
            options={
                'db_table': 'feature_values',
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('accessory_id', models.AutoField(primary_key=True, serialize=False)),
                ('accessory_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='packets.product')),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'db_table': 'accessories',
            },
        ),
        migrations.CreateModel(
            name='ProductContent',
            fields=[
                ('content_id', models.AutoField(primary_key=True, serialize=False)),
                ('hero_image_url', models.URLField(blank=True)),
                ('gallery_urls', models.JSONField(default=list)),
                ('fit_summary', models.TextField(blank=True)),
                ('key_highlights', models.JSONField(default=list)),
                ('best_for', models.CharField(blank=True, max_length=255)),
                ('salesperson_tips', models.JSONField(default=list)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='packets.product')),
            ],
            options={
                'db_table': 'product_content',
            },
        ),
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('default_weights', models.JSONField()),
                ('hard_filters', models.JSONField(null=True)),
                ('stopping_rules', models.JSONField(null=True)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoring_configs', to='packets.packet')),
            ],
            options={
                'db_table': 'scoring_configs',
            },
        ),
    ]
