# Generated by Django 6.0.4 on 2026-04-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComparisonCache',
            fields=[
                ('cache_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_pair_key', models.CharField(db_index=True, help_text='Sorted pair key: "min_id-max_id"', max_length=100)),
                ('feature_set_hash', models.CharField(help_text='SHA-256 digest of combined feature values for both products', max_length=64)),
                ('cmid', models.IntegerField(help_text='Tenant identifier (from CelebrateCompanies)')),
                ('commentary', models.JSONField(help_text='Per-feature commentary from LLM comparison')),
                ('implications', models.JSONField(help_text='Trade-off narratives keyed by product')),
                ('winner_by_feature', models.JSONField(help_text='Which product wins each feature')),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'comparison_cache',
                'unique_together': {('product_pair_key', 'feature_set_hash')},
            },
        ),
    ]
