# Generated by Django 6.0.4 on 2026-04-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmid', models.IntegerField()),
                ('outlet_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField(null=True)),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('event_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='sessions_app.customersession')),
            ],
            options={
                'db_table': 'interaction_events',
            },
        ),
    ]
