# Generated by Django 6.0.4 on 2026-04-08 16:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('cmid', models.IntegerField()),
                ('outlet_id', models.IntegerField(null=True)),
                ('user_id', models.IntegerField()),
                ('packet_id', models.IntegerField(null=True)),
                ('discovery_mode', models.CharField(blank=True, choices=[('voice', 'Voice'), ('text', 'Text'), ('guided', 'Guided')], max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('recommendation_feedback_stars', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_sessions',
            },
        ),
        migrations.CreateModel(
            name='SessionAnswer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('answer_value', models.TextField()),
                ('from_voice', models.BooleanField(default=False)),
                ('score_effect', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='sessions_app.customersession')),
            ],
            options={
                'db_table': 'session_answers',
            },
        ),
    ]
