# Generated by Django 6.0.4 on 2026-04-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('template_id', models.AutoField(primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100)),
                ('template_type', models.CharField(max_length=50)),
                ('template_content', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'prompt_templates',
            },
        ),
        migrations.CreateModel(
            name='LLMCallLog',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_type', models.CharField(max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('cache_hit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_calls', to='sessions_app.customersession')),
            ],
            options={
                'db_table': 'llm_call_logs',
            },
        ),
    ]
