# Generated by Django 6.0.4 on 2026-04-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackPattern',
            fields=[
                ('pattern_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmid', models.IntegerField()),
                ('packet_id', models.IntegerField()),
                ('input_profile_hash', models.CharField(max_length=64)),
                ('product_combination_hash', models.CharField(max_length=64)),
                ('avg_rating', models.FloatField()),
                ('session_count', models.IntegerField()),
                ('pattern_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'feedback_patterns',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('cmid', models.IntegerField()),
                ('outlet_id', models.IntegerField(null=True)),
                ('recommended_products', models.JSONField()),
                ('customer_answers', models.JSONField()),
                ('voice_tags', models.JSONField(null=True)),
                ('scoring_weights', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='sessions_app.customersession')),
            ],
            options={
                'db_table': 'feedback',
            },
        ),
    ]
