# Generated by Django 6.0.4 on 2026-04-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_domain', models.CharField(max_length=255, unique=True)),
                ('description_selector', models.CharField(blank=True, max_length=255)),
                ('gallery_selector', models.CharField(blank=True, max_length=255)),
                ('highlights_selector', models.CharField(blank=True, max_length=255)),
                ('use_llm_fallback', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'crawl_configs',
            },
        ),
        migrations.CreateModel(
            name='CrawledProductContent',
            fields=[
                ('crawl_id', models.AutoField(primary_key=True, serialize=False)),
                ('crawl_url', models.URLField()),
                ('crawl_status', models.CharField(default='pending', max_length=20)),
                ('crawled_description', models.TextField(blank=True)),
                ('crawled_highlights', models.JSONField(default=list)),
                ('crawled_images', models.JSONField(default=list)),
                ('raw_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawled_content', to='packets.product')),
            ],
            options={
                'db_table': 'crawled_product_content',
            },
        ),
    ]
