# Generated by Django 6.0.4 on 2026-04-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('packets', '0001_initial'),
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmid', models.IntegerField()),
                ('outlet_id', models.IntegerField(null=True)),
                ('lead_status', models.CharField(default='new', max_length=20)),
                ('selected_product_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='customers.customerprofile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='sessions_app.customersession')),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='HandoffRequest',
            fields=[
                ('handoff_id', models.AutoField(primary_key=True, serialize=False)),
                ('outlet_id', models.IntegerField()),
                ('product_id', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('discussion_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='leads.lead')),
            ],
            options={
                'db_table': 'handoff_requests',
            },
        ),
        migrations.CreateModel(
            name='LeadCaptureConfig',
            fields=[
                ('config_id', models.AutoField(primary_key=True, serialize=False)),
                ('required_fields', models.JSONField(default=list)),
                ('consent_text', models.TextField()),
                ('email_template_id', models.CharField(blank=True, max_length=100)),
                ('packet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_configs', to='packets.packet')),
            ],
            options={
                'db_table': 'lead_capture_configs',
            },
        ),
        migrations.CreateModel(
            name='ShareEvent',
            fields=[
                ('share_id', models.AutoField(primary_key=True, serialize=False)),
                ('share_method', models.CharField(default='email', max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('ses_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='sessions_app.customersession')),
            ],
            options={
                'db_table': 'share_events',
            },
        ),
    ]
