# Generated by Django 6.0.4 on 2026-04-08 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sessions_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('final_score', models.FloatField()),
                ('match_percentage', models.IntegerField()),
                ('explanation_text', models.TextField(blank=True)),
                ('scoring_breakdown', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='sessions_app.customersession')),
            ],
            options={
                'db_table': 'recommendation_results',
                'ordering': ['rank'],
            },
        ),
    ]
