from __future__ import annotations

from decimal import Decimal
from typing import Any, Callable


def psref_products(svg_data_uri: Callable[[str, str, str, str], str]) -> list[dict[str, Any]]:
    """
    Representative Lenovo PSREF platform catalog.

    PSREF contains many country/MTM variants for the same platform. For ranking
    evaluation, keep one strong platform-level row per meaningful use-case slot
    instead of flooding the recommender with near-duplicate regional SKUs.
    """
    return [
        {
            "product_code": "LEN-IP-SLIM3-15ABR8-R5",
            "model": "IdeaPad Slim 3 15ABR8",
            "family": "Lenovo IdeaPad Slim",
            "price": Decimal("52990"),
            "url": "https://psref.lenovo.com/Product/IdeaPad/IdeaPad_Slim_3_15ABR8",
            "image": svg_data_uri("IdeaPad Slim 3 15", "#C7DDF7", "#253858", "#8FB5E8"),
            "specs": {
                "processor": ("AMD Ryzen 5 7530U", 0.56),
                "ram": ("16 GB soldered DDR4-3200", 0.62),
                "storage": ("512 GB M.2 PCIe SSD", 0.52),
                "display_size": ('15.6" FHD IPS anti-glare, 300 nits', 0.72),
                "battery": ("47 Wh, up to 10 hours MobileMark 2018", 0.46),
                "weight": ("1.62 kg", 0.6),
                "connectivity": ("USB-C, 2x USB-A, HDMI, card reader, Wi-Fi 6", 0.7),
                "build_quality": ("Slim PC-ABS chassis with privacy shutter", 0.48),
                "graphics": ("Integrated AMD Radeon Graphics", 0.3),
                "performance_tier": ("Mainstream everyday performance", None),
                "noise_profile": ("Quiet in light productivity", None),
            },
            "content": {
                "best_for": "Everyday study, browser work, and home productivity",
                "fit_summary": "A practical mainstream choice for students and home users who want a familiar 15.6-inch workspace, solid daily speed, and a full-size keyboard.",
                "key_highlights": ["Ryzen 5 everyday speed", '15.6" IPS display', "Full-size keyboard"],
                "salesperson_tips": [
                    "Use this when the shopper wants a straightforward home or student laptop without gaming-class size.",
                    "The larger display and full keyboard make it easy to position for classes, documents, browsing, and household use.",
                ],
            },
            "accessories": ["15.6-inch Everyday Topload", "Wireless Silent Mouse"],
            "finance": ["No-cost EMI up to 6 months", "Student offer eligibility varies by store"],
        },
        {
            "product_code": "LEN-IP-SLIM3-14IRH10-U5",
            "model": "IdeaPad Slim 3 14IRH10",
            "family": "Lenovo IdeaPad Slim",
            "price": Decimal("49990"),
            "url": "https://psref.lenovo.com/Product/IdeaPad/IdeaPad_Slim_3_14IRH10",
            "image": svg_data_uri("IdeaPad Slim 3 14", "#D8E7FA", "#20324E", "#A6C4EC"),
            "specs": {
                "processor": ("Intel Core 5 210H", 0.62),
                "ram": ("16 GB DDR5", 0.62),
                "storage": ("512 GB M.2 PCIe SSD", 0.52),
                "display_size": ('14" WUXGA IPS anti-glare', 0.58),
                "battery": ("47 Wh battery", 0.46),
                "weight": ("1.39 kg", 0.78),
                "connectivity": ("USB-C, 2x USB-A, HDMI, Wi-Fi 6", 0.68),
                "build_quality": ("Compact everyday chassis with privacy shutter", 0.5),
                "graphics": ("Integrated Intel Graphics", 0.28),
                "performance_tier": ("Compact student and home performance", None),
                "noise_profile": ("Quiet for browser and office work", None),
            },
            "content": {
                "best_for": "Budget-friendly student, home, and travel-light basics",
                "fit_summary": "A compact value pick for shoppers who need everyday browser, school, email, and document work without paying for premium materials or gaming hardware.",
                "key_highlights": ['14" portable body', "16 GB memory", "Value-first pricing"],
                "salesperson_tips": [
                    "Recommend this when budget and portability matter more than a large display.",
                    "It is a clean fit for students, parents, and home users with light daily workloads.",
                ],
            },
            "accessories": ["14-inch Sleeve", "USB-C Travel Adapter"],
            "finance": ["No-cost EMI up to 6 months"],
        },
        {
            "product_code": "LEN-IP-FLEX5-14ABR8-R5",
            "model": "IdeaPad Flex 5 14ABR8",
            "family": "Lenovo IdeaPad Flex",
            "price": Decimal("68990"),
            "url": "https://psref.lenovo.com/Product/IdeaPad/IdeaPad_Flex_5_14ABR8",
            "image": svg_data_uri("IdeaPad Flex 5", "#E2D9FA", "#293052", "#B6A8E8"),
            "specs": {
                "processor": ("AMD Ryzen 5 7530U", 0.56),
                "ram": ("16 GB LPDDR4x", 0.62),
                "storage": ("512 GB M.2 PCIe SSD", 0.52),
                "display_size": ('14" WUXGA IPS touch, 300 nits', 0.58),
                "battery": ("52.5 Wh, up to 10 hours MobileMark 2018", 0.56),
                "weight": ("1.55 kg", 0.68),
                "connectivity": ("USB-C, 2x USB-A, HDMI, SD card reader, Wi-Fi 6", 0.76),
                "build_quality": ("360-degree convertible body with pen support", 0.64),
                "graphics": ("Integrated AMD Radeon Graphics", 0.3),
                "performance_tier": ("Flexible everyday convertible performance", None),
                "noise_profile": ("Quiet for notes, calls, and office work", None),
            },
            "content": {
                "best_for": "Notes, presentations, streaming, and flexible student work",
                "fit_summary": "This is the flexible mainstream pick when touch, tent mode, tablet mode, and pen-friendly workflows matter more than raw graphics power.",
                "key_highlights": ["360-degree hinge", "Touch display", "Pen-friendly workflow"],
                "salesperson_tips": [
                    "Recommend this when the shopper talks about handwritten notes, presentations, couch use, or tablet-style viewing.",
                    "It gives a more adaptable form factor while staying focused on daily productivity.",
                ],
            },
            "accessories": ["Lenovo Digital Pen", "14-inch Sleeve", "USB-C Hub"],
            "finance": ["No-cost EMI up to 9 months"],
        },
        {
            "product_code": "LEN-IP-SLIM5-16IMH10-U7",
            "model": "IdeaPad Slim 5 16IMH10",
            "family": "Lenovo IdeaPad Slim",
            "price": Decimal("82990"),
            "url": "https://psref.lenovo.com/Product/IdeaPad/IdeaPad_Slim_5_16IMH10",
            "image": svg_data_uri("IdeaPad Slim 5 16", "#D7EAF4", "#23324C", "#97C5DE"),
            "specs": {
                "processor": ("Intel Core Ultra 7 255H", 0.86),
                "ram": ("16 GB LPDDR5x", 0.62),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('16" WUXGA / 2.8K OLED-class display options', 0.84),
                "battery": ("70 Wh battery", 0.78),
                "weight": ("1.82 kg", 0.42),
                "connectivity": ("USB-C, USB-A, HDMI, microSD, Wi-Fi 7", 0.82),
                "build_quality": ("Premium mainstream aluminium design", 0.72),
                "graphics": ("Integrated Intel Arc Graphics", 0.46),
                "performance_tier": ("Large-screen premium everyday performance", None),
                "noise_profile": ("Quiet to balanced daily-use tuning", None),
            },
            "content": {
                "best_for": "Streaming, family use, school projects, and large-screen productivity",
                "fit_summary": "A strong large-screen non-gaming option when the shopper wants comfortable viewing, good battery, and smoother multitasking than entry-level systems.",
                "key_highlights": ['16" comfort screen', "Core Ultra performance", "Large battery"],
                "salesperson_tips": [
                    "Use this for home entertainment, parent use, study, and general productivity when a bigger display is a priority.",
                    "It should often beat basic office models for streaming comfort without jumping into gaming weight.",
                ],
            },
            "accessories": ["16-inch Sleeve", "Bluetooth Silent Mouse", "USB-C Travel Hub"],
            "finance": ["No-cost EMI up to 9 months"],
        },
        {
            "product_code": "LEN-TB14-G7-IML-U5H",
            "model": "ThinkBook 14 G7 IML",
            "family": "Lenovo ThinkBook",
            "price": Decimal("82990"),
            "url": "https://psref.lenovo.com/Product/ThinkBook/ThinkBook_14_G7_IML",
            "image": svg_data_uri("ThinkBook 14 G7", "#DCE5F2", "#233147", "#A7B8D5"),
            "specs": {
                "processor": ("Intel Core Ultra 5 125H", 0.78),
                "ram": ("16 GB DDR5-5600", 0.62),
                "storage": ("512 GB M.2 PCIe 4.0 SSD", 0.52),
                "display_size": ('14" WUXGA IPS anti-glare', 0.58),
                "battery": ("60 Wh battery with rapid charge support", 0.68),
                "weight": ("1.36 kg", 0.82),
                "connectivity": ("Thunderbolt 4, USB-C, HDMI, Ethernet, Wi-Fi 6E", 0.88),
                "build_quality": ("Dual-tone aluminium business chassis", 0.76),
                "graphics": ("Integrated Intel Arc Graphics", 0.46),
                "performance_tier": ("AI-ready compact business performance", None),
                "noise_profile": ("Controlled business acoustics", None),
            },
            "content": {
                "best_for": "Compact business work with modern ports",
                "fit_summary": "A strong fit for buyers who want a newer business laptop with AI-ready processing, useful ports, and a lighter 14-inch body.",
                "key_highlights": ["Core Ultra processor", "Thunderbolt 4", "1.36 kg starting weight"],
                "salesperson_tips": [
                    "Use this when the shopper wants business polish but does not need ThinkPad-level ruggedness.",
                    "The port selection helps it stand out for office setups, docks, projectors, and hybrid work.",
                ],
            },
            "accessories": ["ThinkBook Sleeve", "USB-C Dock", "Wireless Mouse"],
            "finance": ["Business EMI options available", "Premium Care upgrade available"],
        },
        {
            "product_code": "LEN-TB16-G7-IML-U7H",
            "model": "ThinkBook 16 G7 IML",
            "family": "Lenovo ThinkBook",
            "price": Decimal("94990"),
            "url": "https://psref.lenovo.com/Product/ThinkBook/ThinkBook_16_G7_IML",
            "image": svg_data_uri("ThinkBook 16 G7", "#D6E0EF", "#202E44", "#98AACB"),
            "specs": {
                "processor": ("Intel Core Ultra 7 155H", 0.86),
                "ram": ("16 GB DDR5-5600", 0.62),
                "storage": ("1 TB M.2 PCIe 4.0 SSD", 0.78),
                "display_size": ('16" WUXGA IPS anti-glare', 0.84),
                "battery": ("71 Wh, up to 11.05 hours MobileMark 25", 0.78),
                "weight": ("1.70 kg", 0.54),
                "connectivity": ("Thunderbolt 4, USB-C, HDMI, Ethernet, Wi-Fi 6E", 0.9),
                "build_quality": ("Large-screen ThinkBook chassis with numeric keypad", 0.74),
                "graphics": ("Integrated Intel Arc Graphics", 0.46),
                "performance_tier": ("Large-screen AI-ready business performance", None),
                "noise_profile": ("Balanced for office multitasking", None),
            },
            "content": {
                "best_for": "Large-screen business multitasking and spreadsheet work",
                "fit_summary": "This is the roomy business pick for users who live in spreadsheets, dashboards, reports, browser tabs, and side-by-side office workflows.",
                "key_highlights": ['16" workspace', "Core Ultra 7", "71 Wh battery"],
                "salesperson_tips": [
                    "Recommend this when the customer wants a larger work canvas but still prefers a business laptop over a gaming chassis.",
                    "The numeric keypad and port mix make it useful for desk-first office users.",
                ],
            },
            "accessories": ["ThinkBook 16-inch Sleeve", "USB-C Universal Dock", "Wireless Keyboard Mouse Combo"],
            "finance": ["Business EMI options available", "No-cost EMI up to 9 months"],
        },
        {
            "product_code": "LEN-TB14-2IN1-G4-IML-U5",
            "model": "ThinkBook 14 2-in-1 G4 IML",
            "family": "Lenovo ThinkBook",
            "price": Decimal("99990"),
            "url": "https://psref.lenovo.com/Product/ThinkBook/ThinkBook_14_2_in_1_G4_IML",
            "image": svg_data_uri("ThinkBook 14 2-in-1", "#E6E1F5", "#28314D", "#B8AED8"),
            "specs": {
                "processor": ("Intel Core Ultra 5 125U", 0.7),
                "ram": ("16 GB DDR5", 0.62),
                "storage": ("512 GB M.2 PCIe SSD", 0.52),
                "display_size": ('14" WUXGA IPS touch, 300 nits', 0.58),
                "battery": ("60 Wh battery", 0.68),
                "weight": ("1.64 kg", 0.58),
                "connectivity": ("Thunderbolt 4, USB-C, HDMI, USB-A, Wi-Fi 6E", 0.86),
                "build_quality": ("Business convertible chassis with pen-ready workflow", 0.78),
                "graphics": ("Integrated Intel Graphics", 0.34),
                "performance_tier": ("Business convertible productivity", None),
                "noise_profile": ("Quiet for meetings, docs, and presentations", None),
            },
            "content": {
                "best_for": "Business notes, presentations, meetings, and flexible work",
                "fit_summary": "A practical business convertible for people who want touch, whiteboarding, presenting, and desk-to-couch flexibility without gaming hardware.",
                "key_highlights": ["2-in-1 business design", "Touch and pen workflow", "Thunderbolt 4"],
                "salesperson_tips": [
                    "Recommend this when flexible form factor and business ports matter together.",
                    "It should sit between consumer Flex/Yoga options and classic clamshell ThinkBooks.",
                ],
            },
            "accessories": ["Lenovo Pen", "USB-C Dock", "14-inch Professional Sleeve"],
            "finance": ["Business EMI options available"],
        },
        {
            "product_code": "LEN-TP-E16-G4-INT-U7",
            "model": "ThinkPad E16 Gen 4 Intel",
            "family": "Lenovo ThinkPad E",
            "price": Decimal("89990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_E16_Gen_4_Intel",
            "image": svg_data_uri("ThinkPad E16 Gen 4", "#D6DCE8", "#1A2230", "#7A88A8"),
            "specs": {
                "processor": ("Intel Core Ultra 7 processor", 0.84),
                "ram": ("16 GB DDR5", 0.62),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('16" WUXGA IPS anti-glare', 0.84),
                "battery": ("64 Wh battery", 0.72),
                "weight": ("1.81 kg class", 0.42),
                "connectivity": ("2x Thunderbolt 4, HDMI, Ethernet, USB-A, Wi-Fi 6E", 0.92),
                "build_quality": ("ThinkPad E-series business chassis", 0.82),
                "graphics": ("Integrated Intel Arc Graphics", 0.46),
                "performance_tier": ("Modern large-screen business performance", None),
                "noise_profile": ("Quiet under office and browser workloads", None),
            },
            "content": {
                "best_for": "Value business work, office productivity, and larger-screen comfort",
                "fit_summary": "A newer large-screen ThinkPad value choice for office users who want ports, durability, keyboard comfort, and a roomy workspace.",
                "key_highlights": ['16" ThinkPad workspace', "2x Thunderbolt 4", "Office-friendly durability"],
                "salesperson_tips": [
                    "Use this as a practical business option when T-series pricing is too high.",
                    "It should rank well for office, spreadsheets, admin workflows, and business buyers who want a larger display.",
                ],
            },
            "accessories": ["ThinkPad Essential Backpack", "USB-C Dock", "Wireless Mouse"],
            "finance": ["Business EMI options available", "Premium Care upgrade available"],
        },
        {
            "product_code": "LEN-TP-L16-G2-AMD-R7",
            "model": "ThinkPad L16 Gen 2 AMD",
            "family": "Lenovo ThinkPad L",
            "price": Decimal("99990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_L16_Gen_2_AMD",
            "image": svg_data_uri("ThinkPad L16 AMD", "#D7DDE7", "#192130", "#7A89A6"),
            "specs": {
                "processor": ("AMD Ryzen 7 PRO processor", 0.78),
                "ram": ("16 GB DDR5", 0.62),
                "storage": ("512 GB M.2 PCIe SSD", 0.52),
                "display_size": ('16" WUXGA IPS anti-glare', 0.84),
                "battery": ("57 Wh battery", 0.62),
                "weight": ("1.82 kg", 0.42),
                "connectivity": ("USB-C, HDMI, Ethernet, USB-A, optional WWAN, Wi-Fi 6E", 0.86),
                "build_quality": ("Serviceable mainstream ThinkPad business chassis", 0.84),
                "graphics": ("Integrated AMD Radeon Graphics", 0.42),
                "performance_tier": ("Mainstream enterprise productivity", None),
                "noise_profile": ("Quiet for enterprise productivity", None),
            },
            "content": {
                "best_for": "Enterprise office work, data entry, admin, and shared teams",
                "fit_summary": "A business workhorse for companies and professionals who value manageability, ports, larger screen comfort, and mainstream performance.",
                "key_highlights": ['16" enterprise workspace', "Ryzen PRO platform", "Serviceable ThinkPad design"],
                "salesperson_tips": [
                    "Recommend this for office fleets, back-office teams, and professionals who need durable mainstream machines.",
                    "It is a good business alternative when premium T/X pricing is unnecessary.",
                ],
            },
            "accessories": ["ThinkPad USB-C Dock", "16-inch Backpack", "Numeric Wireless Keypad"],
            "finance": ["Business EMI options available"],
        },
        {
            "product_code": "LEN-TP-T14-G5-INT-U7",
            "model": "ThinkPad T14 Gen 5 Intel",
            "family": "Lenovo ThinkPad T",
            "price": Decimal("139990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_T14_Gen_5_Intel",
            "image": svg_data_uri("ThinkPad T14 Gen 5", "#D5DAE4", "#151C28", "#7A8498"),
            "specs": {
                "processor": ("Intel Core Ultra 7 155U", 0.78),
                "ram": ("16 GB DDR5", 0.62),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('14" WUXGA IPS low-power anti-glare, 400 nits', 0.6),
                "battery": ("52.5 Wh, up to 11.5 hours MobileMark 25", 0.58),
                "weight": ("1.38 kg with 52.5 Wh battery", 0.8),
                "connectivity": ("2x Thunderbolt 4, HDMI, USB-A, Wi-Fi 6E, optional WWAN", 0.92),
                "build_quality": ("ThinkPad T-series durability, serviceability, and security", 0.94),
                "graphics": ("Integrated Intel Graphics", 0.34),
                "performance_tier": ("Premium business productivity", None),
                "noise_profile": ("Quiet in office and travel workloads", None),
            },
            "content": {
                "best_for": "Premium business travel and IT-managed teams",
                "fit_summary": "This is the safer business recommendation when durability, keyboard feel, security, serviceability, and travel comfort matter together.",
                "key_highlights": ["ThinkPad T durability", "Low carry weight", "Modern business security"],
                "salesperson_tips": [
                    "Use this when reliability and IT-friendly ownership matter more than display flair or gaming performance.",
                    "It should be an easy step-up from E-series when the buyer wants a longer-term business machine.",
                ],
            },
            "accessories": ["ThinkPad 14-inch Sleeve", "USB-C Dock", "Privacy Screen"],
            "finance": ["Business EMI options available", "Premier Support upgrade available"],
        },
        {
            "product_code": "LEN-TP-T16-G4-INT-U7",
            "model": "ThinkPad T16 Gen 4 Intel",
            "family": "Lenovo ThinkPad T",
            "price": Decimal("159990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_T16_Gen_4_Intel",
            "image": svg_data_uri("ThinkPad T16 Gen 4", "#D2D8E3", "#151C28", "#75829A"),
            "specs": {
                "processor": ("Intel Core Ultra 7 processor", 0.84),
                "ram": ("32 GB DDR5", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('16" WUXGA IPS low-power anti-glare', 0.84),
                "battery": ("86 Wh battery option", 0.9),
                "weight": ("1.70 kg class", 0.54),
                "connectivity": ("2x Thunderbolt 4, HDMI, USB-A, Ethernet, Wi-Fi 7, optional WWAN", 0.96),
                "build_quality": ("Premium large-screen ThinkPad business chassis", 0.94),
                "graphics": ("Integrated Intel Arc Graphics", 0.46),
                "performance_tier": ("Premium large-screen business productivity", None),
                "noise_profile": ("Quiet for enterprise productivity", None),
            },
            "content": {
                "best_for": "Premium spreadsheets, business analytics, and desk-first productivity",
                "fit_summary": "A large-screen premium business laptop for users who need ThinkPad reliability, long battery options, and a roomier work surface.",
                "key_highlights": ['16" T-series workspace', "86 Wh battery option", "Premium business ports"],
                "salesperson_tips": [
                    "Use this when a business buyer wants T-series quality but prefers a bigger screen than T14.",
                    "It is well suited for finance, analytics, reporting, and hybrid desk setups.",
                ],
            },
            "accessories": ["ThinkPad USB-C Dock", "16-inch Professional Backpack", "Wireless Numeric Keypad"],
            "finance": ["Business EMI options available", "Premier Support upgrade available"],
        },
        {
            "product_code": "LEN-X1C-G12-U7",
            "model": "ThinkPad X1 Carbon Gen 12",
            "family": "Lenovo ThinkPad X1",
            "price": Decimal("219990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_X1_Carbon_Gen_12",
            "image": svg_data_uri("ThinkPad X1 Carbon G12", "#CFD5E1", "#101722", "#68748D"),
            "specs": {
                "processor": ("Intel Core Ultra 7 155H", 0.86),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('14" 2.8K OLED, 120Hz', 0.62),
                "battery": ("57 Wh, up to 16 hours MobileMark 25 on selected configs", 0.66),
                "weight": ("1.09 kg", 0.96),
                "connectivity": ("2x Thunderbolt 4, HDMI, USB-A, Wi-Fi 6E, optional mobile broadband", 0.94),
                "build_quality": ("Flagship carbon-fiber ThinkPad build", 0.98),
                "graphics": ("Integrated Intel Arc Graphics", 0.46),
                "performance_tier": ("Executive ultraportable performance", None),
                "noise_profile": ("Premium quiet mobility tuning", None),
            },
            "content": {
                "best_for": "Executive travel, premium portability, and polished meetings",
                "fit_summary": "This is the flagship carry machine for people who want ThinkPad credibility, a very light body, premium screen options, and strong meeting-room readiness.",
                "key_highlights": ["1.09 kg class", "2.8K OLED option", "Flagship ThinkPad build"],
                "salesperson_tips": [
                    "Recommend this when the customer repeatedly prioritizes travel comfort, premium feel, and business presence.",
                    "It should win over heavier machines when mobility is the central requirement.",
                ],
            },
            "accessories": ["X1 Leather Sleeve", "Thunderbolt Dock", "USB-C 65W GaN Charger"],
            "finance": ["Premium EMI up to 12 months", "Premier Support upgrade available"],
        },
        {
            "product_code": "LEN-TP-X13-G6-INT-U7",
            "model": "ThinkPad X13 Gen 6 Intel",
            "family": "Lenovo ThinkPad X",
            "price": Decimal("159990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_X13_Gen_6_Intel",
            "image": svg_data_uri("ThinkPad X13 Gen 6", "#D4DAE5", "#121923", "#6C7890"),
            "specs": {
                "processor": ("Intel Core Ultra 7 processor", 0.82),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('13.3" WUXGA IPS low-power anti-glare', 0.48),
                "battery": ("54.7 Wh battery", 0.62),
                "weight": ("1.17 kg class", 0.92),
                "connectivity": ("Thunderbolt 4, HDMI, USB-A, Wi-Fi 7, optional WWAN", 0.92),
                "build_quality": ("Compact ThinkPad business chassis", 0.9),
                "graphics": ("Integrated Intel Graphics", 0.36),
                "performance_tier": ("Compact premium business mobility", None),
                "noise_profile": ("Quiet travel-focused business tuning", None),
            },
            "content": {
                "best_for": "Frequent travel, field work, and compact professional use",
                "fit_summary": "A small premium ThinkPad for people who need business-grade security and ports in a more compact package than 14-inch systems.",
                "key_highlights": ['13.3" compact body', "ThinkPad security", "Travel-friendly weight"],
                "salesperson_tips": [
                    "Recommend this when the user values mobility over screen size but still wants a full business laptop.",
                    "It is stronger for consultants, sales teams, and field professionals than home entertainment buyers.",
                ],
            },
            "accessories": ["ThinkPad 13-inch Sleeve", "USB-C Travel Hub", "Privacy Screen"],
            "finance": ["Business EMI options available"],
        },
        {
            "product_code": "LEN-TP-X1-2IN1-G9-U7",
            "model": "ThinkPad X1 2-in-1 Gen 9",
            "family": "Lenovo ThinkPad X1",
            "price": Decimal("239990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_X1_2_in_1_Gen_9",
            "image": svg_data_uri("ThinkPad X1 2-in-1 G9", "#D8D6E5", "#151A27", "#807B9D"),
            "specs": {
                "processor": ("Intel Core Ultra 7 155U", 0.78),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('14" WUXGA / 2.8K OLED touch', 0.62),
                "battery": ("57 Wh battery", 0.66),
                "weight": ("1.35 kg class", 0.82),
                "connectivity": ("2x Thunderbolt 4, HDMI, USB-A, Wi-Fi 6E, optional WWAN", 0.94),
                "build_quality": ("Flagship ThinkPad convertible chassis", 0.96),
                "graphics": ("Integrated Intel Graphics", 0.36),
                "performance_tier": ("Executive convertible productivity", None),
                "noise_profile": ("Premium quiet meeting and travel tuning", None),
            },
            "content": {
                "best_for": "Executive notes, tablet mode, travel, and client presentations",
                "fit_summary": "This is the premium business convertible for users who need ThinkPad quality plus handwritten notes, tent mode, and presentation flexibility.",
                "key_highlights": ["X1 convertible design", "Premium touch display", "Business travel ready"],
                "salesperson_tips": [
                    "Use this when the buyer wants X1-class build plus tablet and pen workflows.",
                    "It should not be positioned as a value pick; it is about premium flexibility and business confidence.",
                ],
            },
            "accessories": ["ThinkPad Pen", "X1 Sleeve", "Thunderbolt Dock"],
            "finance": ["Premium EMI up to 12 months", "Premier Support upgrade available"],
        },
        {
            "product_code": "LEN-TP-Z13-G2-AMD-R7",
            "model": "ThinkPad Z13 Gen 2",
            "family": "Lenovo ThinkPad Z",
            "price": Decimal("189990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_Z13_Gen_2",
            "image": svg_data_uri("ThinkPad Z13 Gen 2", "#E1D9CF", "#191D22", "#9A8778"),
            "specs": {
                "processor": ("AMD Ryzen 7 PRO 7840U", 0.76),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('13.3" 2.8K OLED touch', 0.48),
                "battery": ("51.5 Wh battery", 0.58),
                "weight": ("1.19 kg class", 0.9),
                "connectivity": ("USB4, Wi-Fi 6E, Bluetooth, premium webcam", 0.78),
                "build_quality": ("Premium compact ThinkPad Z design", 0.92),
                "graphics": ("Integrated AMD Radeon 780M Graphics", 0.5),
                "performance_tier": ("Premium AMD business mobility", None),
                "noise_profile": ("Quiet premium mobility tuning", None),
            },
            "content": {
                "best_for": "Premium compact business, meetings, and travel",
                "fit_summary": "A stylish compact ThinkPad for buyers who want premium materials, strong AMD efficiency, and a high-quality screen in a travel-friendly body.",
                "key_highlights": ["Compact premium design", "OLED touch option", "Ryzen PRO platform"],
                "salesperson_tips": [
                    "Recommend this when the buyer wants something more distinctive than a classic ThinkPad but still business-oriented.",
                    "It is best for premium mobility, not large-screen spreadsheet work.",
                ],
            },
            "accessories": ["USB-C Travel Dock", "Premium Sleeve", "Wireless Mouse"],
            "finance": ["Premium EMI up to 12 months"],
        },
        {
            "product_code": "LEN-P14S-G5-AMD-R7",
            "model": "ThinkPad P14s Gen 5 AMD",
            "family": "Lenovo ThinkPad P",
            "price": Decimal("169990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_P14s_Gen_5_AMD",
            "image": svg_data_uri("ThinkPad P14s AMD", "#D4D9E3", "#151B25", "#738096"),
            "specs": {
                "processor": ("AMD Ryzen 7 PRO 8840HS", 0.88),
                "ram": ("32 GB DDR5", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('14" 2.8K OLED, 120Hz, 100% DCI-P3', 0.62),
                "battery": ("52.5 Wh battery", 0.58),
                "weight": ("1.31 kg", 0.86),
                "connectivity": ("2x Thunderbolt 4, HDMI, USB-A, Ethernet, Wi-Fi 6E", 0.94),
                "build_quality": ("Mobile workstation-class ThinkPad chassis", 0.96),
                "graphics": ("Integrated AMD Radeon 780M Graphics", 0.5),
                "performance_tier": ("Portable workstation performance", None),
                "noise_profile": ("Workstation cooling under heavier professional loads", None),
            },
            "content": {
                "best_for": "Engineering, analytics, coding, and professional productivity",
                "fit_summary": "This is the compact professional pick when the buyer needs stronger CPU headroom, workstation credibility, serviceability, and serious business connectivity without moving to a bulky discrete-GPU laptop.",
                "key_highlights": ["Ryzen 7 PRO", "Workstation-class positioning", "Strong business ports"],
                "salesperson_tips": [
                    "Use this for engineers, analysts, developers, and professional users who want reliability with more headroom than mainstream business laptops.",
                    "It bridges the gap between standard ThinkPads and heavier creator, workstation, or gaming systems.",
                ],
            },
            "accessories": ["ThinkPad Thunderbolt Dock", "Mobile Workstation Sleeve", "USB-C Ethernet Adapter"],
            "finance": ["Business EMI options available", "Premier Support upgrade available"],
        },
        {
            "product_code": "LEN-TP-P16S-G3-INT-U7",
            "model": "ThinkPad P16s Gen 3 Intel",
            "family": "Lenovo ThinkPad P",
            "price": Decimal("189990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_P16s_Gen_3_Intel",
            "image": svg_data_uri("ThinkPad P16s Gen 3", "#D5DAE1", "#151B25", "#768294"),
            "specs": {
                "processor": ("Intel Core Ultra 7 155H", 0.86),
                "ram": ("32 GB DDR5", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('16" WUXGA / 2.8K OLED workstation display options', 0.84),
                "battery": ("86 Wh battery option", 0.9),
                "weight": ("1.70 kg class", 0.54),
                "connectivity": ("Thunderbolt 4, HDMI, Ethernet, USB-A, Wi-Fi 6E", 0.94),
                "build_quality": ("Large-screen mobile workstation ThinkPad chassis", 0.96),
                "graphics": ("Integrated Intel Arc Graphics or optional professional graphics", 0.58),
                "performance_tier": ("Large-screen professional workstation productivity", None),
                "noise_profile": ("Workstation cooling for sustained professional workloads", None),
            },
            "content": {
                "best_for": "Coding, engineering, data work, CAD-light, and large-screen pro use",
                "fit_summary": "A professional step-up for users who want workstation positioning, large-screen comfort, and better sustained headroom without jumping to a heavy P16.",
                "key_highlights": ['16" workstation screen', "86 Wh option", "Professional ThinkPad build"],
                "salesperson_tips": [
                    "Use this when the shopper is professional, technical, or developer-heavy and wants a larger screen than P14s.",
                    "It is a better coding/engineering fit than consumer thin-and-lights when reliability and ports matter.",
                ],
            },
            "accessories": ["ThinkPad Thunderbolt Dock", "16-inch Workstation Backpack", "USB-C Monitor Cable"],
            "finance": ["Business EMI options available", "Premier Support upgrade available"],
        },
        {
            "product_code": "LEN-TP-P1-G7-U9-4060",
            "model": "ThinkPad P1 Gen 7",
            "family": "Lenovo ThinkPad P",
            "price": Decimal("289990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_P1_Gen_7",
            "image": svg_data_uri("ThinkPad P1 Gen 7", "#D4D8E0", "#121821", "#727D90"),
            "specs": {
                "processor": ("Intel Core Ultra 9 185H", 0.94),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('16" 4K OLED / WQUXGA professional display options', 0.92),
                "battery": ("90 Wh battery", 0.92),
                "weight": ("1.82 kg class", 0.42),
                "connectivity": ("Thunderbolt 4, HDMI, SD Express, Wi-Fi 7", 0.96),
                "build_quality": ("Premium thin mobile workstation chassis", 0.98),
                "graphics": ("NVIDIA RTX 4060 / professional GPU-class options", 0.92),
                "performance_tier": ("Premium creator and workstation performance", None),
                "noise_profile": ("Performance workstation acoustics under heavy load", None),
            },
            "content": {
                "best_for": "Professional creators, CAD-light workflows, rendering, ML prototyping, and heavy coding",
                "fit_summary": "This is the premium workstation choice when the buyer needs serious CPU/GPU headroom, a professional display, and ThinkPad build quality in a thinner chassis.",
                "key_highlights": ["Core Ultra 9", "Professional 16-inch display", "Discrete RTX-class graphics"],
                "salesperson_tips": [
                    "Recommend this only when professional workloads justify workstation pricing.",
                    "It is overkill for everyday Office but appropriate for engineers, creators, and technical power users.",
                ],
            },
            "accessories": ["ThinkPad Thunderbolt Workstation Dock", "Professional Backpack", "4K Monitor Cable"],
            "finance": ["Business EMI options available", "Premier Support upgrade available"],
        },
        {
            "product_code": "LEN-TP-P16-G2-I9-ADA",
            "model": "ThinkPad P16 Gen 2",
            "family": "Lenovo ThinkPad P",
            "price": Decimal("389990"),
            "url": "https://psref.lenovo.com/Product/ThinkPad/ThinkPad_P16_Gen_2",
            "image": svg_data_uri("ThinkPad P16 Gen 2", "#CED3DC", "#101820", "#6C7686"),
            "specs": {
                "processor": ("Intel Core i9 HX-series", 0.98),
                "ram": ("64 GB DDR5 ECC-capable class", 1.0),
                "storage": ("2 TB M.2 PCIe SSD", 0.96),
                "display_size": ('16" WQUXGA OLED / factory-calibrated workstation display', 0.94),
                "battery": ("94 Wh battery", 0.94),
                "weight": ("2.95 kg class", 0.02),
                "connectivity": ("Thunderbolt 4, HDMI, Ethernet, SD card, Wi-Fi 6E", 0.98),
                "build_quality": ("Full-size ISV-oriented mobile workstation chassis", 1.0),
                "graphics": ("NVIDIA RTX 4000 Ada-class professional GPU", 1.0),
                "performance_tier": ("Full mobile workstation performance", None),
                "noise_profile": ("Workstation-class cooling under sustained heavy load", None),
            },
            "content": {
                "best_for": "CAD, simulation, 3D rendering, data science, and workstation replacement",
                "fit_summary": "A no-compromise workstation entry for workloads where sustained CPU/GPU power, ISV credibility, and large memory capacity matter more than portability.",
                "key_highlights": ["HX-series CPU", "RTX Ada professional GPU", "Full workstation chassis"],
                "salesperson_tips": [
                    "Use this only for clearly workstation-grade workloads.",
                    "It should rank below lighter systems unless the customer explicitly needs CAD, simulation, rendering, or professional GPU power.",
                ],
            },
            "accessories": ["ThinkPad Workstation Dock", "17-inch Workstation Backpack", "External Monitor Bundle"],
            "finance": ["Business EMI options available", "Premier Support upgrade available"],
        },
        {
            "product_code": "LEN-YOGA-S7-14ILL10-U7",
            "model": "Yoga Slim 7 14ILL10",
            "family": "Lenovo Yoga",
            "price": Decimal("134990"),
            "url": "https://psref.lenovo.com/Product/Yoga/Yoga_Slim_7_14ILL10",
            "image": svg_data_uri("Yoga Slim 7 14", "#E7E2F7", "#29304E", "#B9B0E7"),
            "specs": {
                "processor": ("Intel Core Ultra 7 258V", 0.88),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('14" 2.8K OLED touch, 120Hz', 0.62),
                "battery": ("70 Wh battery", 0.8),
                "weight": ("1.28 kg class", 0.88),
                "connectivity": ("Thunderbolt 4, USB-C, USB-A, HDMI, Wi-Fi 7", 0.88),
                "build_quality": ("Premium thin aluminium Yoga chassis", 0.9),
                "graphics": ("Integrated Intel Arc Graphics 140V", 0.46),
                "performance_tier": ("Premium media and productivity ultraportable", None),
                "noise_profile": ("Quiet premium mobility tuning", None),
            },
            "content": {
                "best_for": "Premium video watching, travel, productivity, and sharp display use",
                "fit_summary": "A premium thin-and-light for people who care about screen quality, battery, smooth everyday performance, and carrying comfort.",
                "key_highlights": ["2.8K OLED touch", "70 Wh battery", "Light premium build"],
                "salesperson_tips": [
                    "Recommend this for shoppers who want excellent display quality without gaming weight.",
                    "It should do well for video watching, productivity, travel, and premium home use.",
                ],
            },
            "accessories": ["Yoga Sleeve", "USB-C 65W GaN Charger", "Bluetooth Silent Mouse"],
            "finance": ["Premium EMI up to 12 months"],
        },
        {
            "product_code": "LEN-YOGA-9-2IN1-14ILL10-U7",
            "model": "Yoga 9 2-in-1 14ILL10",
            "family": "Lenovo Yoga",
            "price": Decimal("169990"),
            "url": "https://psref.lenovo.com/Product/Yoga/Yoga_9_2_in_1_14ILL10",
            "image": svg_data_uri("Yoga 9 2-in-1", "#F0DDE9", "#2B304E", "#D8AFC8"),
            "specs": {
                "processor": ("Intel Core Ultra 7 258V", 0.88),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('14" 2.8K OLED touch, 120Hz', 0.62),
                "battery": ("75 Wh battery", 0.84),
                "weight": ("1.32 kg class", 0.86),
                "connectivity": ("2x Thunderbolt 4, USB-C, USB-A, Wi-Fi 7", 0.88),
                "build_quality": ("Premium convertible Yoga chassis with pen support", 0.96),
                "graphics": ("Integrated Intel Arc Graphics 140V", 0.46),
                "performance_tier": ("Premium convertible media and productivity", None),
                "noise_profile": ("Quiet premium convertible tuning", None),
            },
            "content": {
                "best_for": "Premium video watching, couch use, note-taking, and flexible family use",
                "fit_summary": "This is a strong premium fit when display quality, speakers, touch, tent mode, and easy viewing angles matter more than raw gaming performance.",
                "key_highlights": ["OLED touch display", "Convertible form factor", "Premium media experience"],
                "salesperson_tips": [
                    "Use this for buyers who mention couch or bed viewing, tablet mode, handwritten notes, or premium entertainment.",
                    "It should beat basic clamshells when comfort and display quality are central.",
                ],
            },
            "accessories": ["Yoga Pen", "Yoga Sleeve", "USB-C Travel Dock"],
            "finance": ["Premium EMI up to 12 months", "Premium Care included on select units"],
        },
        {
            "product_code": "LEN-YOGA-BOOK9-14IAH10-U7",
            "model": "Yoga Book 9 14IAH10",
            "family": "Lenovo Yoga",
            "price": Decimal("224990"),
            "url": "https://psref.lenovo.com/Product/Yoga/Yoga_Book_9_14IAH10",
            "image": svg_data_uri("Yoga Book 9", "#E9DDF4", "#2C3150", "#C3AEDC"),
            "specs": {
                "processor": ("Intel Core Ultra 7 255H", 0.86),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('Dual 14" 2.8K OLED touch displays', 0.9),
                "battery": ("88 Wh battery", 0.9),
                "weight": ("1.22 kg tablet body plus keyboard accessories", 0.82),
                "connectivity": ("Thunderbolt 4, USB-C, Wi-Fi 7, folio keyboard ecosystem", 0.84),
                "build_quality": ("Premium dual-screen Yoga design", 0.98),
                "graphics": ("Integrated Intel Arc Graphics", 0.46),
                "performance_tier": ("Dual-screen premium productivity and creator workflow", None),
                "noise_profile": ("Premium quiet mobility tuning", None),
            },
            "content": {
                "best_for": "Dual-screen multitasking, presentations, creators, and premium novelty",
                "fit_summary": "A specialized premium machine for shoppers who explicitly want dual-screen workflows, presentations, creative ideation, or a standout device.",
                "key_highlights": ["Dual OLED displays", "Premium Yoga ecosystem", "Flexible multitasking modes"],
                "salesperson_tips": [
                    "Recommend this only when the user values dual-screen flexibility and premium experience.",
                    "It is not the default value pick for simple home or office use.",
                ],
            },
            "accessories": ["Bluetooth Keyboard", "Yoga Pen", "Folio Stand"],
            "finance": ["Premium EMI up to 12 months"],
        },
        {
            "product_code": "LEN-YOGA-PRO7-14AHP9-R7",
            "model": "Yoga Pro 7 14AHP9",
            "family": "Lenovo Yoga",
            "price": Decimal("149990"),
            "url": "https://psref.lenovo.com/Product/Yoga/Yoga_Pro_7_14AHP9",
            "image": svg_data_uri("Yoga Pro 7", "#E4DDF4", "#283151", "#B4A8DE"),
            "specs": {
                "processor": ("AMD Ryzen 7 8845HS", 0.88),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('14.5" 2.8K OLED / IPS-class creator display', 0.7),
                "battery": ("73 Wh battery", 0.82),
                "weight": ("1.49 kg integrated graphics / 1.64 kg discrete graphics", 0.64),
                "connectivity": ("USB4, USB-C, HDMI 2.1, USB-A, Wi-Fi 6E", 0.88),
                "build_quality": ("Premium aluminium creator chassis", 0.9),
                "graphics": ("Integrated AMD Radeon 780M Graphics", 0.5),
                "performance_tier": ("Premium creator and productivity performance", None),
                "noise_profile": ("Performance-tuned but portable creator thermals", None),
            },
            "content": {
                "best_for": "Coding, productivity, light creator work, and sharp display needs",
                "fit_summary": "This is the premium non-gaming performance pick when the shopper wants a sharper screen, strong multitasking, and more CPU headroom than a standard thin-and-light.",
                "key_highlights": ["Ryzen 7 HS-class chip", "Creator display", "73 Wh battery"],
                "salesperson_tips": [
                    "Recommend this for light-to-moderate creative work, heavier multitasking, coding, and customers who care about screen quality.",
                    "It offers more performance character than an everyday Yoga while staying much easier to carry than gaming systems.",
                ],
            },
            "accessories": ["Yoga Sleeve", "USB-C Creator Dock", "Bluetooth Mouse"],
            "finance": ["Premium EMI up to 12 months"],
        },
        {
            "product_code": "LEN-YOGA-PRO9-16IMH9-U9-4060",
            "model": "Yoga Pro 9i 16IMH9",
            "family": "Lenovo Yoga",
            "price": Decimal("239990"),
            "url": "https://psref.lenovo.com/Product/Yoga/Yoga_Pro_9_16IMH9",
            "image": svg_data_uri("Yoga Pro 9i 16", "#EFE2F3", "#2B2F4A", "#CBAFDD"),
            "specs": {
                "processor": ("Intel Core Ultra 9 185H", 0.94),
                "ram": ("32 GB LPDDR5x", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('16" 3.2K Mini LED / high-gamut creator display', 0.94),
                "battery": ("84 Wh battery", 0.88),
                "weight": ("2.05 kg class", 0.28),
                "connectivity": ("Thunderbolt 4, USB-C, HDMI 2.1, SD card, Wi-Fi 6E", 0.94),
                "build_quality": ("Premium creator chassis with high-end display", 0.96),
                "graphics": ("NVIDIA GeForce RTX 4060 Laptop GPU", 0.94),
                "performance_tier": ("Premium creator and AI performance", None),
                "noise_profile": ("Creator-class cooling under rendering load", None),
            },
            "content": {
                "best_for": "Video editing, design, rendering, creators, and premium display work",
                "fit_summary": "A high-end creator laptop for buyers who care about screen quality, GPU acceleration, color-sensitive work, and premium performance without choosing a gaming-branded system.",
                "key_highlights": ["Mini LED creator display", "RTX 4060", "Core Ultra 9"],
                "salesperson_tips": [
                    "Use this for creators, editors, designers, and power users who want a premium display-first machine.",
                    "It should not outrank simpler laptops unless creative or display-heavy needs are explicit.",
                ],
            },
            "accessories": ["Creator Sleeve", "USB-C Creator Dock", "Color Calibration Service"],
            "finance": ["Premium EMI up to 12 months"],
        },
        {
            "product_code": "LEN-V14-G4-IRU-I3",
            "model": "Lenovo V14 Gen 4 IRU",
            "family": "Lenovo V Series",
            "price": Decimal("38990"),
            "url": "https://psref.lenovo.com/Product/Lenovo/Lenovo_V14_G4_IRU",
            "image": svg_data_uri("Lenovo V14 G4", "#C8D8EF", "#1F2A3B", "#86A2C9"),
            "specs": {
                "processor": ("13th Gen Intel Core i3", 0.42),
                "ram": ("8 GB DDR4", 0.32),
                "storage": ("512 GB M.2 PCIe SSD", 0.52),
                "display_size": ('14" FHD anti-glare', 0.56),
                "battery": ("38 Wh battery", 0.26),
                "weight": ("1.43 kg class", 0.76),
                "connectivity": ("USB-C, USB-A, HDMI, Ethernet, Wi-Fi 5/6", 0.62),
                "build_quality": ("Entry business chassis with privacy shutter on selected configs", 0.4),
                "graphics": ("Integrated Intel Graphics", 0.22),
                "performance_tier": ("Entry office and admin performance", None),
                "noise_profile": ("Quiet for light office tasks", None),
            },
            "content": {
                "best_for": "Budget office, billing, email, and basic admin",
                "fit_summary": "A low-cost Lenovo business-style laptop for simple office, email, web portals, and front-desk tasks where budget matters most.",
                "key_highlights": ['14" compact body', "SSD storage", "Value office choice"],
                "salesperson_tips": [
                    "Use this for price-sensitive buyers with simple workloads.",
                    "Avoid recommending it for heavy multitasking, coding, creative work, or premium entertainment.",
                ],
            },
            "accessories": ["Essential Topload", "Wired Mouse"],
            "finance": ["No-cost EMI up to 6 months"],
        },
        {
            "product_code": "LEN-V17-G4-IRU-I5",
            "model": "Lenovo V17 Gen 4 IRU",
            "family": "Lenovo V Series",
            "price": Decimal("58990"),
            "url": "https://psref.lenovo.com/Product/Lenovo/Lenovo_V17_G4_IRU",
            "image": svg_data_uri("Lenovo V17 G4", "#CAD8EE", "#1F2A3B", "#8BA4C8"),
            "specs": {
                "processor": ("13th Gen Intel Core i5", 0.58),
                "ram": ("16 GB DDR4", 0.62),
                "storage": ("512 GB M.2 PCIe SSD", 0.52),
                "display_size": ('17.3" FHD anti-glare', 0.92),
                "battery": ("45 Wh battery", 0.38),
                "weight": ("2.02 kg class", 0.3),
                "connectivity": ("USB-C, USB-A, HDMI, Ethernet, Wi-Fi 6", 0.66),
                "build_quality": ("Large entry business chassis with numeric keypad", 0.46),
                "graphics": ("Integrated Intel Graphics", 0.26),
                "performance_tier": ("Large-screen value office performance", None),
                "noise_profile": ("Quiet in light office use", None),
            },
            "content": {
                "best_for": "Large-screen home office, seniors, spreadsheets, and desk use",
                "fit_summary": "A value-oriented large-screen choice when the shopper wants readability and desk comfort more than portability or premium build.",
                "key_highlights": ['17.3" large display', "Numeric keypad", "Budget large-screen option"],
                "salesperson_tips": [
                    "Recommend this for desk-first users, seniors, and spreadsheet-heavy value buyers.",
                    "It is less suitable for frequent carry or premium streaming comfort.",
                ],
            },
            "accessories": ["17-inch Topload", "Wireless Keyboard Mouse Combo"],
            "finance": ["No-cost EMI up to 6 months"],
        },
        {
            "product_code": "LEN-LOQ-15AHP9-R7-4060",
            "model": "Lenovo LOQ 15AHP9",
            "family": "Lenovo LOQ",
            "price": Decimal("109990"),
            "url": "https://psref.lenovo.com/Product/LOQ/LOQ_15AHP9",
            "image": svg_data_uri("LOQ 15AHP9", "#EFD7CE", "#282330", "#DCA38E"),
            "specs": {
                "processor": ("AMD Ryzen 7 8845HS", 0.9),
                "ram": ("16 GB DDR5", 0.62),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('15.6" FHD IPS, 144Hz', 0.76),
                "battery": ("60 Wh battery", 0.62),
                "weight": ("2.38 kg", 0.12),
                "connectivity": ("USB-C 10Gbps with DP, HDMI, Ethernet, 3x USB-A, Wi-Fi 6", 0.88),
                "build_quality": ("Gaming chassis with rear-heavy port layout", 0.74),
                "graphics": ("NVIDIA GeForce RTX 4060 Laptop GPU 8 GB", 0.96),
                "performance_tier": ("Strong mainstream gaming performance", None),
                "noise_profile": ("Audible under gaming load, calmer in quiet mode", None),
            },
            "content": {
                "best_for": "Gaming, 3D, video editing, and graphics-heavy student work",
                "fit_summary": "This is the stronger LOQ option when the conversation clearly needs a real GPU for modern games, 3D tools, rendering, or heavier creator workloads.",
                "key_highlights": ["RTX 4060", "Ryzen 7 HS-class processor", "144Hz display"],
                "salesperson_tips": [
                    "Use this when the shopper needs more graphics headroom than integrated laptops or RTX 4050 options.",
                    "It should not be pushed for simple office or study use unless gaming or GPU-heavy work is a clear requirement.",
                ],
            },
            "accessories": ["Gaming Backpack", "Gaming Mouse", "Cooling Stand"],
            "finance": ["No-cost EMI up to 12 months", "Accidental damage protection available"],
        },
        {
            "product_code": "LEN-LOQ-15IRX10-I7-5060",
            "model": "Lenovo LOQ 15IRX10",
            "family": "Lenovo LOQ",
            "price": Decimal("124990"),
            "url": "https://psref.lenovo.com/Product/LOQ/LOQ_15IRX10",
            "image": svg_data_uri("LOQ 15IRX10", "#F0D9D1", "#282230", "#DCA08C"),
            "specs": {
                "processor": ("Intel Core i7 HX-class processor", 0.92),
                "ram": ("24 GB DDR5", 0.82),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('15.6" FHD / WQHD high-refresh gaming display', 0.82),
                "battery": ("60 Wh battery", 0.62),
                "weight": ("2.40 kg class", 0.12),
                "connectivity": ("USB-C, HDMI, Ethernet, USB-A, Wi-Fi 6", 0.88),
                "build_quality": ("Updated LOQ gaming chassis with strong cooling", 0.78),
                "graphics": ("NVIDIA GeForce RTX 5060 Laptop GPU-class option", 0.98),
                "performance_tier": ("Upper-mainstream gaming and creator performance", None),
                "noise_profile": ("Gaming acoustics under sustained load", None),
            },
            "content": {
                "best_for": "Modern gaming, GPU-heavy school work, Blender, and editing",
                "fit_summary": "A stronger mainstream gaming pick when the user wants newer GPU headroom and sustained performance but does not need Legion premium build.",
                "key_highlights": ["RTX 50-class option", "HX-class CPU", "High-refresh gaming display"],
                "salesperson_tips": [
                    "Recommend this for value-minded gamers and students with GPU-heavy work.",
                    "Avoid it for parent streaming, email, or lightweight productivity profiles.",
                ],
            },
            "accessories": ["LOQ Gaming Backpack", "Gaming Mouse", "Headset"],
            "finance": ["No-cost EMI up to 12 months"],
        },
        {
            "product_code": "LEN-LEGION5-15IAX10-U7-5060",
            "model": "Legion 5 15IAX10",
            "family": "Lenovo Legion",
            "price": Decimal("154990"),
            "url": "https://psref.lenovo.com/Product/Legion/Legion_5_15IAX10",
            "image": svg_data_uri("Legion 5 15", "#E8D6F0", "#241B2E", "#B98CCC"),
            "specs": {
                "processor": ("Intel Core Ultra 7 HX-class processor", 0.94),
                "ram": ("32 GB DDR5", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('15" OLED / high-refresh gaming display', 0.86),
                "battery": ("80 Wh battery", 0.86),
                "weight": ("2.0 kg class", 0.3),
                "connectivity": ("USB-C, HDMI 2.1, Ethernet, multiple USB-A, Wi-Fi 7", 0.94),
                "build_quality": ("Legion gaming chassis with stronger thermals", 0.88),
                "graphics": ("NVIDIA GeForce RTX 5060 Laptop GPU-class option", 0.98),
                "performance_tier": ("Premium-mainstream gaming performance", None),
                "noise_profile": ("Gaming-class cooling with balanced modes", None),
            },
            "content": {
                "best_for": "Gaming, game broadcasting, creator workloads, and high-refresh display needs",
                "fit_summary": "A balanced Legion option for shoppers who want more refinement than LOQ, stronger gaming performance, and a better display experience.",
                "key_highlights": ["Legion thermal design", "High-refresh display", "RTX 50-class option"],
                "salesperson_tips": [
                    "Use this when gaming is clearly important but the buyer does not need the heaviest Pro model.",
                    "It can also serve creators who want GPU power without workstation pricing.",
                ],
            },
            "accessories": ["Legion Backpack", "Legion Gaming Mouse", "Gaming Headset"],
            "finance": ["No-cost EMI up to 12 months"],
        },
        {
            "product_code": "LEN-LEGION-P5-16IRX9-I7-4070",
            "model": "Legion Pro 5 16IRX9",
            "family": "Lenovo Legion",
            "price": Decimal("189990"),
            "url": "https://psref.lenovo.com/Product/Legion/Legion_Pro_5_16IRX9",
            "image": svg_data_uri("Legion Pro 5 16", "#E6D2EE", "#22192D", "#B58AC8"),
            "specs": {
                "processor": ("14th Gen Intel Core i7-14650HX", 0.96),
                "ram": ("32 GB DDR5", 0.96),
                "storage": ("1 TB M.2 PCIe 4.0 SSD", 0.78),
                "display_size": ('16" WQXGA IPS, 240Hz', 0.92),
                "battery": ("80 Wh battery", 0.86),
                "weight": ("2.50 kg", 0.08),
                "connectivity": ("2x USB-C, 4x USB-A, HDMI 2.1, Ethernet, Wi-Fi 6E", 0.96),
                "build_quality": ("Legion Pro cooling and aluminium top chassis", 0.9),
                "graphics": ("NVIDIA GeForce RTX 4070 Laptop GPU 8 GB", 1.0),
                "performance_tier": ("High-end gaming and creator performance", None),
                "noise_profile": ("Gaming-class cooling with performance acoustics", None),
            },
            "content": {
                "best_for": "High-end gaming, rendering, heavy editing, and GPU headroom",
                "fit_summary": "This is the power-first recommendation when the shopper wants serious GPU capability, a faster 16-inch gaming display, and sustained performance for demanding workloads.",
                "key_highlights": ["RTX 4070", '16" WQXGA 240Hz display', "HX-series processor"],
                "salesperson_tips": [
                    "Use this only when the shopper is clearly asking for high-end games, 3D rendering, heavy video work, or long-term GPU headroom.",
                    "If daily carry matters more than power, steer the conversation back toward Yoga, ThinkPad, or ThinkBook options.",
                ],
            },
            "accessories": ["Legion Armored Backpack", "Legion Gaming Mouse", "RGB Headset"],
            "finance": ["No-cost EMI up to 12 months", "Accidental damage protection available"],
        },
        {
            "product_code": "LEN-LEGION7-16IAX10-U9-5070",
            "model": "Legion 7 16IAX10",
            "family": "Lenovo Legion",
            "price": Decimal("229990"),
            "url": "https://psref.lenovo.com/Product/Legion/Legion_7_16IAX10",
            "image": svg_data_uri("Legion 7 16", "#E8D4F0", "#23182E", "#BB8CD1"),
            "specs": {
                "processor": ("Intel Core Ultra 9 HX-class processor", 0.98),
                "ram": ("32 GB DDR5", 0.96),
                "storage": ("1 TB M.2 PCIe SSD", 0.78),
                "display_size": ('16" WQXGA / OLED high-refresh gaming display', 0.94),
                "battery": ("84 Wh battery", 0.88),
                "weight": ("2.0 kg class", 0.3),
                "connectivity": ("Thunderbolt 4, USB-C, HDMI 2.1, Ethernet, Wi-Fi 7", 0.96),
                "build_quality": ("Premium Legion gaming and creator chassis", 0.94),
                "graphics": ("NVIDIA GeForce RTX 5070 Laptop GPU-class option", 1.0),
                "performance_tier": ("Premium gaming and creator performance", None),
                "noise_profile": ("High-performance gaming cooling with balanced modes", None),
            },
            "content": {
                "best_for": "Premium gaming, creator work, game broadcasting, and display-first power users",
                "fit_summary": "A premium gaming/creator option for people who want strong GPU performance, better display quality, and more polish than mainstream gaming laptops.",
                "key_highlights": ["RTX 50-class graphics", "Premium Legion design", "High-refresh 16-inch display"],
                "salesperson_tips": [
                    "Recommend this for serious gamers and creators who also care about fit and finish.",
                    "It remains overkill for basic student, parent, email, and office-only profiles.",
                ],
            },
            "accessories": ["Legion 16-inch Backpack", "Gaming Mouse", "USB-C Monitor Cable"],
            "finance": ["No-cost EMI up to 12 months"],
        },
        {
            "product_code": "LEN-LEGION-P7-16IAX10H-U9-5080",
            "model": "Legion Pro 7 16IAX10H",
            "family": "Lenovo Legion",
            "price": Decimal("349990"),
            "url": "https://psref.lenovo.com/Product/Legion/Legion_Pro_7_16IAX10H",
            "image": svg_data_uri("Legion Pro 7 16", "#E5D0ED", "#21172B", "#B684C8"),
            "specs": {
                "processor": ("Intel Core Ultra 9 HX-class processor", 1.0),
                "ram": ("64 GB DDR5", 1.0),
                "storage": ("2 TB M.2 PCIe SSD", 0.96),
                "display_size": ('16" WQXGA OLED / 240Hz high-end gaming display', 0.96),
                "battery": ("99.9 Wh battery", 0.98),
                "weight": ("2.72 kg class", 0.04),
                "connectivity": ("Thunderbolt 4, USB-C, HDMI 2.1, 2.5GbE Ethernet, Wi-Fi 7", 1.0),
                "build_quality": ("Flagship Legion Pro chassis with advanced cooling", 0.98),
                "graphics": ("NVIDIA GeForce RTX 5080 Laptop GPU-class option", 1.0),
                "performance_tier": ("Flagship gaming and creator performance", None),
                "noise_profile": ("Flagship gaming cooling with high load acoustics", None),
            },
            "content": {
                "best_for": "Flagship gaming, 3D rendering, AI workloads, and max-performance buyers",
                "fit_summary": "A flagship performance system for shoppers who explicitly need top-tier gaming or GPU compute headroom and accept size, noise, and price tradeoffs.",
                "key_highlights": ["Flagship RTX-class GPU", "99.9 Wh battery", "Legion Pro thermal design"],
                "salesperson_tips": [
                    "Use this only when the user asks for maximum gaming, rendering, or GPU power.",
                    "It should be penalized for simple everyday, parent, office, or portability-first profiles.",
                ],
            },
            "accessories": ["Legion Armored Backpack", "Premium Gaming Mouse", "Gaming Headset"],
            "finance": ["No-cost EMI up to 12 months", "Accidental damage protection available"],
        },
        {
            "product_code": "LEN-CHROME-DUET-11M889",
            "model": "Lenovo Chromebook Duet 11",
            "family": "Lenovo Chromebook",
            "price": Decimal("29990"),
            "url": "https://psref.lenovo.com/Product/Lenovo/Lenovo_Chromebook_Duet_11M889",
            "image": svg_data_uri("Chromebook Duet 11", "#DDEBE8", "#1D3430", "#93C4BD"),
            "specs": {
                "processor": ("MediaTek Kompanio tablet-class processor", 0.22),
                "ram": ("8 GB LPDDR4x", 0.32),
                "storage": ("128 GB eMMC / UFS storage", 0.24),
                "display_size": ('10.95" 2K touch display', 0.36),
                "battery": ("29 Wh tablet battery", 0.36),
                "weight": ("0.51 kg tablet, keyboard sold/bundled by config", 1.0),
                "connectivity": ("USB-C, Wi-Fi 6, Bluetooth", 0.48),
                "build_quality": ("Detachable tablet design with folio keyboard ecosystem", 0.58),
                "graphics": ("Integrated ARM graphics", 0.12),
                "performance_tier": ("ChromeOS tablet and school basics", None),
                "noise_profile": ("Fanless silent tablet operation", None),
            },
            "content": {
                "best_for": "Kids, school basics, web apps, streaming, and ultra-light tablet use",
                "fit_summary": "A lightweight ChromeOS detachable for simple web, classroom, video, and family tablet use where Windows apps and heavy multitasking are not required.",
                "key_highlights": ["Detachable tablet", "Fanless silent use", "ChromeOS simplicity"],
                "salesperson_tips": [
                    "Recommend this only when ChromeOS and web-first usage are acceptable.",
                    "It is not suitable for Windows software, coding, gaming, or heavy office workloads.",
                ],
            },
            "accessories": ["Folio Keyboard", "USI Pen", "USB-C Charger"],
            "finance": ["No-cost EMI up to 6 months"],
        },
    ]
